# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout Alexandria
      uses: actions/checkout@v2
      with:
        name: g2forge/alexandria
        path: alexandria
    - name: Build Alexandria
      working-directory: ./alexandria
      run: pwd -P && ls -al && mvn -B install --file pom.xml -P release
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: enigma
    - name: Build with Maven
      working-directory: ./enigma
      run: pwd -P && ls -al && mvn -B package --file pom.xml -P release
